import { CaseStudyContent } from "@/types/content";

export const workContent: Record<string, CaseStudyContent> = {
  "sri-nantha-glasses": {
    id: "sri-nantha-glasses",
    slug: "sri-nantha-glasses",
    client: "Sri Nantha Glasses & Stickers",
    category: "Custom Web Application & Operational System",
    industry: "Manufacturing & Commercial Glass",
    summary: "Digitized custom glass quote requests, order specifications, and customer inquiry tracking into a unified web application.",
    context: "Sri Nantha Glasses & Stickers is a commercial glass and decorative sticker manufacturer serving architectural and commercial buyers across South India.",
    problem: "Custom glass measurements and specs were handled manually via phone calls and paper notes, causing quote bottlenecks and customer follow-up delays.",
    discovery: "Buyers needed immediate clarity on custom glass pricing options and a fast way to submit precise architectural measurements without waiting for callbacks.",
    approach: "We mapped Sri Nantha's quote calculation workflow and engineered a responsive web platform with an integrated custom quote request system.",
    interventions: [
      {
        title: "Quote Request Engine",
        description: "Built a structured multi-step glass and sticker specification selector.",
      },
      {
        title: "Brand & Catalog Architecture",
        description: "Designed a clean product showcase reflecting their technical capabilities.",
      },
      {
        title: "Automated Inquiry Routing",
        description: "Connected web quote submissions directly to staff notification channels.",
      },
    ],
    system: "Redwolf BUILD + DEFINE Digital Intervention",
    outcome: "Eliminated quote response delays, enabled instant specification intake, and established a professional web presence reflecting commercial scale.",
    evidence: ["Digitized quote intake workflow", "Structured architectural glass catalog"],
    learning: "Complex industrial product inquiries are best solved when the customer can specify parameters upfront in a structured digital interface.",
    nextStep: "Expand customer self-service portal for real-time order status tracking.",
    capabilitiesUsed: ["BUILD", "DEFINE"],
    solutionsInvolved: ["build", "define"],
    relatedIndustrySlug: "manufacturing",
    relatedInsightSlugs: ["local-seo-google-maps-pack-ranking-strategy"],
    featured: true,
    seo: {
      title: "Sri Nantha Glasses & Stickers — Case Study | Redwolf Intervention",
      description: "How Redwolf digitized custom glass quote requests and product specification intake into a custom web application platform.",
      keywords: ["custom glass quote app", "manufacturing case study", "commercial glass software", "Redwolf case study"],
    },
  },
  "mahalakshmi-tours": {
    id: "mahalakshmi-tours",
    slug: "mahalakshmi-tours",
    client: "Mahalakshmi Tours & Travels",
    category: "Tour Discovery & WhatsApp Booking System",
    industry: "Travel & Hospitality",
    summary: "Built an interactive tour itinerary discovery platform with instant WhatsApp package booking integration.",
    context: "Mahalakshmi Tours & Travels operates regional pilgrimage, heritage, and holiday tour packages across South India.",
    problem: "High website traffic wasn't converting into direct package inquiries because itineraries were static and quote requests required long forms.",
    discovery: "Regional travelers preferred discussing tour customization on WhatsApp immediately after viewing package highlights on mobile devices.",
    approach: "We redesigned the tour catalog around visual package highlights and added 1-tap WhatsApp booking triggers populated with selected package details.",
    interventions: [
      {
        title: "Interactive Tour Showcase",
        description: "Structured day-wise itinerary displays with transparent inclusions.",
      },
      {
        title: "WhatsApp Booking Engine",
        description: "Engineered deep-linked WhatsApp CTA buttons pre-populating tour details.",
      },
      {
        title: "Mobile Optimization",
        description: "Optimized mobile performance for fast loading on 3G/4G networks.",
      },
    ],
    system: "Redwolf GROW + DEFINE Digital Intervention",
    outcome: "Dramatically increased direct package inquiry rate and reduced average booking conversation cycle.",
    evidence: ["Instant 1-tap WhatsApp booking triggers", "Mobile-first itinerary layouts"],
    learning: "Friction-free messaging triggers out-perform complex multi-step booking forms for regional consumer travel.",
    nextStep: "Deploy multi-language tour itineraries to capture international regional travelers.",
    capabilitiesUsed: ["GROW", "DEFINE"],
    solutionsInvolved: ["grow", "define"],
    relatedIndustrySlug: "travel-hospitality",
    relatedInsightSlugs: ["scaling-meta-google-ads-cpa-reduction-funnel-guide"],
    featured: true,
    seo: {
      title: "Mahalakshmi Tours & Travels — Case Study | Redwolf Intervention",
      description: "How Redwolf transformed static tour package listings into an interactive WhatsApp booking platform for Mahalakshmi Tours.",
      keywords: ["tour booking app case study", "WhatsApp booking system", "travel web design", "Redwolf case study"],
    },
  },
  "gateway-holidays": {
    id: "gateway-holidays",
    slug: "gateway-holidays",
    client: "Gateway Holidays",
    category: "Customer Acquisition & Digital Positioning Platform",
    industry: "Travel & Hospitality",
    summary: "Positioned Gateway Holidays as a premier international tour provider and scaled customer acquisition via performance ads.",
    context: "Gateway Holidays provides outbound international vacation packages and customized holiday itineraries for families and corporate groups.",
    problem: "Struggled to stand out from generic travel agencies and needed a predictable stream of qualified holiday inquiries.",
    discovery: "Premium travelers evaluate holiday providers based on itinerary clarity, destination expertise, and transparent pricing options.",
    approach: "We redefined their digital brand positioning, built high-converting landing pages, and launched intent-targeted Google & Meta search campaigns.",
    interventions: [
      {
        title: "Brand Positioning System",
        description: "Clarified international holiday value proposition and luxury travel messaging.",
      },
      {
        title: "High-Converting Destination Pages",
        description: "Built dedicated landing pages for popular destinations (Dubai, Europe, SE Asia).",
      },
      {
        title: "Targeted Search Ads Architecture",
        description: "Deployed intent-driven search campaign structures with server-side conversion tracking.",
      },
    ],
    system: "Redwolf GROW + DEFINE Intervention",
    outcome: "Established clear market differentiation and generated a steady flow of high-intent international travel inquiries.",
    evidence: ["Intent-driven search campaign architecture", "Dedicated destination landing pages"],
    learning: "Positioning clarity combined with intent-driven search targeting yields significantly higher inquiry conversion rates.",
    nextStep: "Integrate custom itinerary builder for self-service holiday planning.",
    capabilitiesUsed: ["GROW", "DEFINE"],
    solutionsInvolved: ["grow", "define"],
    relatedIndustrySlug: "travel-hospitality",
    relatedInsightSlugs: [
      "scaling-meta-google-ads-cpa-reduction-funnel-guide",
      "how-to-rank-on-chatgpt-perplexity-gemini-geo-guide",
    ],
    featured: true,
    seo: {
      title: "Gateway Holidays — Case Study | Redwolf Intervention",
      description: "How Redwolf positioned Gateway Holidays as a premier international tour provider and scaled qualified lead acquisition.",
      keywords: ["travel lead generation case study", "performance search ads", "destination landing pages", "Redwolf case study"],
    },
  },
};
