import { IndustryContent } from "@/types/content";

export const industriesContent: Record<string, IndustryContent> = {
  "fmcg-distribution": {
    id: "fmcg-distribution",
    slug: "fmcg-distribution",
    name: "FMCG & Distribution",
    heroHeadline: "Field Sales, Van Inventory & Beat Route Digitization",
    businessReality: "FMCG distributors manage hundreds of retail shops over sprawling rural and semi-urban routes. Manual order taking, paper invoices, unmonitored retailer credit, and van stock discrepancies limit daily sales throughput.",
    problems: [
      "Field sales reps take orders on paper clipboards or WhatsApp messages.",
      "Van sales inventory discrepancies occur between main warehouse and field stock.",
      "Retailer credit limits are exceeded without real-time manager approval.",
      "Network connectivity dead-zones cause standard cloud mobile applications to crash.",
    ],
    opportunities: [
      "Deploy offline-first mobile order taking with instant Bluetooth thermal printing.",
      "Automate daily van inventory loading approvals and reconciliation.",
      "Enforce automatic retailer credit limit controls at point of order capture.",
    ],
    relevantRedwolfSystems: [
      "EasyTrack FMCG Distribution Platform",
      "Offline-First Field Mobile Sync Engine",
      "Retailer Credit & Ledger Control Console",
    ],
    relevantSolutionSlugs: ["build", "productize", "grow"],
    relatedWorkSlugs: ["easytrack"],
    relatedInsightSlugs: ["local-seo-google-maps-pack-ranking-strategy"],
    cta: {
      label: "Explore FMCG Solutions",
      labelWithArrow: "Explore FMCG Solutions →",
      href: "/industries/fmcg-distribution",
      variant: "primary",
    },
    seo: {
      title: "FMCG & Distribution Digital Systems | Redwolf Industry Solutions",
      description: "Digitize FMCG field sales, van inventory loading, rural beat routes, and retailer credit management with Redwolf offline-first software systems.",
      keywords: ["FMCG distribution software", "field sales app", "van inventory management", "beat route sales"],
    },
  },
  healthcare: {
    id: "healthcare",
    slug: "healthcare",
    name: "Healthcare",
    heroHeadline: "Patient Booking, Clinical Portals & Trust Architecture",
    businessReality: "Hospitals, clinics, and diagnostic chains lose qualified patient bookings due to cluttered websites, friction-filled appointment flows, and lack of clear clinical specialty presentation.",
    problems: [
      "Patients struggle to find specialty doctors and available consultation slots.",
      "Diagnostic package inquiries get lost across manual phone calls and front-desk desks.",
      "Clinical trust is weakened by non-responsive legacy hospital portals.",
    ],
    opportunities: [
      "Engineer friction-free patient appointment booking engines.",
      "Design clear specialty doctor directories with verified patient credentials.",
      "Implement local search optimization (AEO/GEO) for regional clinic discoverability.",
    ],
    relevantRedwolfSystems: [
      "Patient Appointment Intake Systems",
      "Clinical Specialty Directory Engine",
      "Local Healthcare AEO/GEO Discoverability",
    ],
    relevantSolutionSlugs: ["define", "grow", "build"],
    relatedWorkSlugs: ["sri-nantha-glasses"],
    relatedInsightSlugs: ["local-seo-google-maps-pack-ranking-strategy"],
    cta: {
      label: "Explore Healthcare Solutions",
      labelWithArrow: "Explore Healthcare Solutions →",
      href: "/industries/healthcare",
      variant: "primary",
    },
    seo: {
      title: "Healthcare & Clinic Digital Systems | Redwolf Industry Solutions",
      description: "Friction-free patient appointment intake, doctor specialty directories, and local search discoverability for hospitals and clinics.",
      keywords: ["healthcare web app", "patient booking portal", "clinic local SEO", "hospital website engineering"],
    },
  },
  manufacturing: {
    id: "manufacturing",
    slug: "manufacturing",
    name: "Manufacturing",
    heroHeadline: "Custom Quote Systems, Dealer Portals & Workflow Automation",
    businessReality: "Manufacturers lose high-value enterprise contracts when custom quote requests take days to process through disconnected spreadsheets, paper drawings, and email chains.",
    problems: [
      "Custom product pricing and quote generation depend on manual engineering estimates.",
      "Dealers have no self-service portal to check order status or download technical specs.",
      "Lead follow-up speed for industrial inquiries is slow.",
    ],
    opportunities: [
      "Build automated custom quote configurators based on customer specifications.",
      "Launch secure dealer portals for order tracking and technical spec access.",
      "Streamline commercial lead intake directly into production queues.",
    ],
    relevantRedwolfSystems: [
      "Custom Quote Configurator Engine",
      "Dealer & Buyer Self-Service Portal",
      "Industrial Lead Intake & Production Queue Sync",
    ],
    relevantSolutionSlugs: ["build", "define"],
    relatedWorkSlugs: ["sri-nantha-glasses"],
    relatedInsightSlugs: ["scaling-meta-google-ads-cpa-reduction-funnel-guide"],
    cta: {
      label: "Explore Manufacturing Solutions",
      labelWithArrow: "Explore Manufacturing Solutions →",
      href: "/industries/manufacturing",
      variant: "primary",
    },
    seo: {
      title: "Manufacturing & Industrial Digital Systems | Redwolf Industry Solutions",
      description: "Custom quote generation systems, dealer self-service portals, and industrial lead intake automation for manufacturing enterprises.",
      keywords: ["manufacturing web app", "custom quote configurator", "dealer portal software", "industrial lead automation"],
    },
  },
  "travel-hospitality": {
    id: "travel-hospitality",
    slug: "travel-hospitality",
    name: "Travel & Hospitality",
    heroHeadline: "Tour Discovery, Itinerary Customizer & WhatsApp Booking Systems",
    businessReality: "Tour operators and hospitality providers lose booking conversions when itineraries are buried in generic PDFs, response times are slow, and travelers cannot request instant WhatsApp custom packages.",
    problems: [
      "Tour packages are static PDFs or unoptimized web pages.",
      "Travelers drop off when custom itinerary requests require waiting 24 hours for email quotes.",
      "Direct website bookings are low compared to high-commission OTA aggregators.",
    ],
    opportunities: [
      "Build interactive itinerary customization modules directly on web platforms.",
      "Integrate instant 1-tap WhatsApp package inquiry triggers.",
      "Scale direct customer discovery via performance search ads and landing page architecture.",
    ],
    relevantRedwolfSystems: [
      "Interactive Tour Itinerary Customizer",
      "Instant WhatsApp Inquiry Integration Engine",
      "Direct Booking Landing Page System",
    ],
    relevantSolutionSlugs: ["grow", "define", "build"],
    relatedWorkSlugs: ["mahalakshmi-tours", "gateway-holidays"],
    relatedInsightSlugs: ["scaling-meta-google-ads-cpa-reduction-funnel-guide"],
    cta: {
      label: "Explore Travel Solutions",
      labelWithArrow: "Explore Travel Solutions →",
      href: "/industries/travel-hospitality",
      variant: "primary",
    },
    seo: {
      title: "Travel & Hospitality Digital Systems | Redwolf Industry Solutions",
      description: "Interactive tour itinerary builders, WhatsApp booking triggers, and direct customer discovery systems for tour operators and resorts.",
      keywords: ["travel booking software", "tour itinerary builder", "WhatsApp booking system", "resort direct booking"],
    },
  },
  smes: {
    id: "smes",
    slug: "smes",
    name: "SMEs & Growing Businesses",
    heroHeadline: "Enterprise Digital Transformation for Ambitious SMEs",
    businessReality: "Growing businesses outgrow fragmented off-the-shelf tools and basic brochure websites, needing integrated systems that support their expanding market scale.",
    problems: [
      "Brand messaging doesn't reflect the company's evolved capabilities.",
      "Lead data is scattered across email inboxes, messaging apps, and local files.",
      "Marketing spend lacks clear attribution back to revenue.",
    ],
    opportunities: [
      "Define clear market positioning and modern brand architecture.",
      "Build unified web application platforms connecting customer touchpoints.",
      "Implement intent-driven customer acquisition systems.",
    ],
    relevantRedwolfSystems: [
      "SME Brand & Positioning Architecture",
      "Unified Lead & Invoicing Web Application",
      "Growth Analytics & Customer Discovery Engine",
    ],
    relevantSolutionSlugs: ["define", "grow", "build"],
    relatedWorkSlugs: ["sri-nantha-glasses", "mahalakshmi-tours"],
    relatedInsightSlugs: [
      "how-to-rank-on-chatgpt-perplexity-gemini-geo-guide",
      "local-seo-google-maps-pack-ranking-strategy",
    ],
    cta: {
      label: "Explore SME Solutions",
      labelWithArrow: "Explore SME Solutions →",
      href: "/industries/smes",
      variant: "primary",
    },
    seo: {
      title: "SME Digital Transformation | Redwolf Industry Solutions",
      description: "Enterprise strategy, brand positioning, custom web engineering, and customer growth systems tailored for ambitious growing businesses.",
      keywords: ["SME digital transformation", "growing business software", "brand positioning SME", "custom business systems"],
    },
  },
};
